name: DevOps Practice CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Show all files for debugging
      - name: List all files
        run: ls -R

      # Step 3: Show Docker version
      - name: Docker version
        run: docker --version

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build --progress=plain -t devops-practice:latest .

      # Step 5: Run Docker container
      - name: Run Docker container
        run: docker run --rm devops-practice:latest

